controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

infrastructure_controllers:
    resource:
        path: ../src/Infrastructure/Http/
        namespace: App\Infrastructure\Http
    type: attribute
